### ISSUE TITLE
Upper Camel Case and Lower Camel Case

### ISSUE THREAD

**Issue by ShinokiRyosei** [kentyDev/queueDrop#15]
https://en.wikipedia.org/wiki/Camel_case

protocol, classとinstanceを見分けるために、class, protocol, structはupper camel caseで書いて、instance, variableはlower camel caseで書くのが大事

命名とかはクオリティ担保のためと、チーム開発では必須やから守っとこう

**Comment by kentyDev** [comment]
ありがとうございます！！修正しておきました！

**Comment by ShinokiRyosei** [comment]
LGTM
