### ISSUE TITLE
循環参照を防ぐ

### ISSUE THREAD

**Issue by ShinokiRyosei** [kentyDev/queueDrop#17]
ごめん。
循環参照が英語でなんていうかわからんけど
https://github.com/kentyDev/queueDrop/blob/master/queueDrop/HomeViewControllerDelegate.swift#L11

ここで

```swift

protocol HomeViewControllerDelegate: class { }
```
って`: class`ってつけとくと、

`HomeViewController`側で
```swift 
weak var delegate: HomeViewControllerDelegate?
```
ってできて、循環参照防げるから、オススメ

**Comment by kentyDev** [comment]
ありがとうございます！一応変更しておきました！
Apple のSwift本には基本Strongと書かれていたと思ったのですがこういう場合はweak の方がいいのでしょうか？

**Comment by ShinokiRyosei** [comment]
うん
Delegateはクラスが継承するなら、`: class`をつけて、`weak`にするのが一般的。

**Comment by kentyDev** [comment]
OKです！ありがとうございます！
